/// <reference types="./mod.d.ts" />
/// <reference lib="dom" />
import { c3 } from './core.js'

import './polyfill.js'
import './api.axis.js'
import './api.category.js'
import './api.chart.js'
import './api.color.js'
import './api.data.js'
import './api.donut.js'
import './api.flow.js'
import './api.focus.js'
import './api.grid.js'
import './api.group.js'
import './api.legend.js'
import './api.load.js'
import './api.pie.js'
import './api.region.js'
import './api.selection.js'
import './api.show.js'
import './api.subchart.js'
import './api.tooltip.js'
import './api.transform.js'
import './api.x.js'
import './api.zoom.js'
import './arc.js'
import './axis.js'
import './cache.js'
import './category.js'
import './class.js'
import './class-utils.js'
import './clip.js'
import './color.js'
import './config.js'
import './data.convert.js'
import './data.js'
import './data.load.js'
import './domain.js'
import './drag.js'
import './format.js'
import './grid.js'
import './interaction.js'
import './legend.js'
import './region.js'
import './scale.js'
import './selection.js'
import './shape.bar.js'
import './shape.js'
import './shape.line.js'
import './size.js'
import './subchart.js'
import './text.js'
import './title.js'
import './colorscale.js'
import './stanford.js'
import './stanfordelements.js'
import './tooltip.js'
import './type.js'
import './ua.js'
import './util.js'
import './zoom.js'

export default c3
